import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Session } from "@/context/Session";
import { Query } from "@/context/Query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clone Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session>
          <Query>{children}</Query>
        </Session>
      </body>
    </html>
  );
}
